name: 03b-node-js-build
on:
  push:
    branches:
      - "master"
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node: 20
      - run: npm ci
      - run: npm test
