name: 05 - Verificación - información - runner
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: imprimir información OS
        run: echo  ${{"os": runner.os}}
      - name: imprimir arquitectura
        run: echo ${{"arch": runner.arch}}
