name: 05 - Verificación - información - runner
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir información OS y arquitectura
        run: |
          echo "os: ${{runner.os}}"
          echo "arch: ${{ runner.arch}}"
