name: 06 - Número Aleatoreo entre 1 y 10
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Número Aleatorio
        run: | 
          echo "RANDOM_NUMBER=$(shuf -i 1-10 -n 1)" >> $GITHUB_ENV

      - name: Mostrar Número
        run: | 
          echo "🎲 El valor del dado es: $RANDOM_NUMBER"