name: 06 - Número Aleatoreo entre 1 y 10
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Número Aleatorio
        run: |
          echo "{env_var}={value}" >> "$GITHUB_ENV"
          random_number=$((1 + RANDOM % 10))
          echo "El valor del dado es: $random_number"