name: 06b - Ejercicio
on:
  push:
    branches:
      - "master"
jobs:
  random-num:
    runs-on: ubuntu-latest
    steps:
      - name: Número aleatorio
        run: |
          echo "random_number=$((1 + RANDOM % 10))" >> "$GITHUB_ENV"
      - name:
          run: echo "número aleatorio es $random_number"

