name: 06b - Ejercicio
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  random-num:
    runs-on: ubuntu-latest
    steps:
      - name: Variable random
        run: |
          echo "random_number=$((1 + RANDOM % 10))" >> "$GITHUB_ENV"

      - name: Número aleatorio
        run: echo "número aleatorio es ${{env.random_number}}"

