name: 10a - entornos
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  entornos:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Verificar variable
        run: echo ${{vars.UNA_VARIABLE}}
      - name: Verificar secretos
        run: echo ${{secrets.UN_SECRETO}}